### ISSUE TITLE
behave_pandas library does not work for numpy >= 1.24

### ISSUE THREAD

**Issue by pixelthedatafreak** [clembou/behave-pandas#19]
- As from numpy 1.24 [(release notes)](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations) numpy.float, numpy.int and similar aliases were removed from the library , causing errors when they are used.

- Since there are occurrences of np.float and np.int in the code,  they should be replaced with plain Python float and int.

Source : https://stackoverflow.com/questions/74844262/how-to-solve-error-numpy-has-no-attribute-float-in-python

**Comment by clembou** [comment]
Thanks for the head's up. Is this something you would be able to raise a PR for?

**Comment by pixelthedatafreak** [comment]
Yes, sure :)

**Comment by lkacenja** [comment]
Hi, I've added a PR that fixes this for us, #20. I'm a little new to making contributions to python projects, so I apologize if I've done something odd. Thanks!

**Comment by clembou** [comment]
@pixelthedatafreak  @lkacenja I just released v0.5.0 of the library that should include @lkacenja 's PR + other minor build / packaging cleanups. Please give it a try and let me know if anything is broken!
